// <auto-generated />
namespace MortgageHelperData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class datetimenulled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimenulled));
        
        string IMigrationMetadata.Id
        {
            get { return "202012012243294_datetimenulled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
